"""
Railway Domain Vocabulary & Acoustic Knowledge Base
Contains standardized station names, codes, aliases, terminology,
and acoustic Keyterm Prompting / Keyword configurations for Deepgram Flux and Nova STT.
"""
from typing import Dict, List, Set, Tuple

# 1. Standard Stations: Code -> Metadata
STATIONS: Dict[str, Dict[str, str]] = {
    "NJP": {
        "code": "NJP",
        "name": "New Jalpaiguri",
        "aliases": ["New Jalpaiguri Junction", "NJP Railway Station", "Siliguri NJP"],
        "city": "Siliguri / Jalpaiguri",
        "state": "West Bengal",
    },
    "HWH": {
        "code": "HWH",
        "name": "Howrah",
        "aliases": ["Howrah Junction", "Haora", "Howrah Railway Station"],
        "city": "Kolkata / Howrah",
        "state": "West Bengal",
    },
    "SDAH": {
        "code": "SDAH",
        "name": "Sealdah",
        "aliases": ["Sealdah Junction", "Sealdaha", "Sealdah Railway Station"],
        "city": "Kolkata",
        "state": "West Bengal",
    },
    "KOAA": {
        "code": "KOAA",
        "name": "Kolkata",
        "aliases": ["Kolkata Chitpur", "Calcutta", "Kolkata Railway Station"],
        "city": "Kolkata",
        "state": "West Bengal",
    },
    "NDLS": {
        "code": "NDLS",
        "name": "New Delhi",
        "aliases": ["New Delhi Railway Station", "NDLS"],
        "city": "Delhi",
        "state": "Delhi",
    },
    "DLI": {
        "code": "DLI",
        "name": "Delhi",
        "aliases": ["Old Delhi", "Delhi Junction", "Old Delhi Railway Station"],
        "city": "Delhi",
        "state": "Delhi",
    },
    "KGP": {
        "code": "KGP",
        "name": "Kharagpur",
        "aliases": ["Kharagpur Junction", "Kharagpur Station"],
        "city": "Kharagpur",
        "state": "West Bengal",
    },
    "BWN": {
        "code": "BWN",
        "name": "Barddhaman",
        "aliases": ["Burdwan", "Bardhaman", "Barddhaman Junction"],
        "city": "Barddhaman",
        "state": "West Bengal",
    },
    "DGR": {
        "code": "DGR",
        "name": "Durgapur",
        "aliases": ["Durgapur Railway Station"],
        "city": "Durgapur",
        "state": "West Bengal",
    },
    "ASN": {
        "code": "ASN",
        "name": "Asansol",
        "aliases": ["Asansol Junction", "Asansol Station"],
        "city": "Asansol",
        "state": "West Bengal",
    },
    "MLDT": {
        "code": "MLDT",
        "name": "Malda",
        "aliases": ["Malda Town", "Malda Railway Station"],
        "city": "Malda",
        "state": "West Bengal",
    },
    "PNBE": {
        "code": "PNBE",
        "name": "Patna",
        "aliases": ["Patna Junction", "Patna Station"],
        "city": "Patna",
        "state": "Bihar",
    },
    "GHY": {
        "code": "GHY",
        "name": "Guwahati",
        "aliases": ["Guwahati Railway Station"],
        "city": "Guwahati",
        "state": "Assam",
    },
    "RNC": {
        "code": "RNC",
        "name": "Ranchi",
        "aliases": ["Ranchi Junction", "Ranchi Station"],
        "city": "Ranchi",
        "state": "Jharkhand",
    },
    "BBS": {
        "code": "BBS",
        "name": "Bhubaneswar",
        "aliases": ["Bhubaneswar Railway Station"],
        "city": "Bhubaneswar",
        "state": "Odisha",
    },
    "SGUJ": {
        "code": "SGUJ",
        "name": "Siliguri",
        "aliases": ["Siliguri Junction", "Siliguri Town"],
        "city": "Siliguri",
        "state": "West Bengal",
    },
}

# 2. Canonical Name & Code Lookup Maps
CANONICAL_STATION_NAMES: Dict[str, str] = {
    "njp": "NJP",
    "new jalpaiguri": "New Jalpaiguri",
    "new jalpaiguri junction": "New Jalpaiguri",
    "howrah": "Howrah",
    "howrah junction": "Howrah Junction",
    "hwh": "HWH",
    "sealdah": "Sealdah",
    "sealdah junction": "Sealdah Junction",
    "sdah": "SDAH",
    "kolkata": "Kolkata",
    "koaa": "KOAA",
    "delhi": "Delhi",
    "old delhi": "Delhi",
    "new delhi": "New Delhi",
    "ndls": "NDLS",
    "kharagpur": "Kharagpur",
    "kharagpur junction": "Kharagpur Junction",
    "kgp": "KGP",
    "barddhaman": "Barddhaman",
    "burdwan": "Barddhaman",
    "bardhaman": "Barddhaman",
    "barddhaman junction": "Barddhaman",
    "bwn": "BWN",
    "durgapur": "Durgapur",
    "dgr": "DGR",
    "asansol": "Asansol",
    "asansol junction": "Asansol",
    "asn": "ASN",
    "malda": "Malda",
    "malda town": "Malda",
    "mldt": "MLDT",
    "patna": "Patna",
    "patna junction": "Patna",
    "pnbe": "PNBE",
    "guwahati": "Guwahati",
    "ghy": "GHY",
    "ranchi": "Ranchi",
    "rnc": "RNC",
    "bhubaneswar": "Bhubaneswar",
    "bbs": "BBS",
    "siliguri": "Siliguri",
    "sguj": "SGUJ",
}

# 2b. Station Name/Alias to Code Map
STATION_CODE_MAP: Dict[str, str] = {
    "njp": "NJP",
    "new jalpaiguri": "NJP",
    "new jalpaiguri junction": "NJP",
    "howrah": "HWH",
    "howrah junction": "HWH",
    "hwh": "HWH",
    "haora": "HWH",
    "sealdah": "SDAH",
    "sealdah junction": "SDAH",
    "sealdaha": "SDAH",
    "sdah": "SDAH",
    "kolkata": "KOAA",
    "calcutta": "KOAA",
    "koaa": "KOAA",
    "delhi": "DLI",
    "old delhi": "DLI",
    "dli": "DLI",
    "new delhi": "NDLS",
    "ndls": "NDLS",
    "kharagpur": "KGP",
    "kharagpur junction": "KGP",
    "kgp": "KGP",
    "barddhaman": "BWN",
    "burdwan": "BWN",
    "bardhaman": "BWN",
    "barddhaman junction": "BWN",
    "bwn": "BWN",
    "durgapur": "DGR",
    "dgr": "DGR",
    "asansol": "ASN",
    "asansol junction": "ASN",
    "asn": "ASN",
    "malda": "MLDT",
    "malda town": "MLDT",
    "mldt": "MLDT",
    "patna": "PNBE",
    "patna junction": "PNBE",
    "pnbe": "PNBE",
    "guwahati": "GHY",
    "ghy": "GHY",
    "ranchi": "RNC",
    "rnc": "RNC",
    "bhubaneswar": "BBS",
    "bbs": "BBS",
    "siliguri": "SGUJ",
    "sguj": "SGUJ",
}

# Station Code to Pretty Name
STATION_NAME_MAP: Dict[str, str] = {
    "NJP": "New Jalpaiguri (NJP)",
    "HWH": "Howrah (HWH)",
    "SDAH": "Sealdah (SDAH)",
    "KOAA": "Kolkata (KOAA)",
    "NDLS": "New Delhi (NDLS)",
    "DLI": "Delhi (DLI)",
    "KGP": "Kharagpur (KGP)",
    "BWN": "Barddhaman (BWN)",
    "DGR": "Durgapur (DGR)",
    "ASN": "Asansol (ASN)",
    "MLDT": "Malda Town (MLDT)",
    "PNBE": "Patna (PNBE)",
    "GHY": "Guwahati (GHY)",
    "RNC": "Ranchi (RNC)",
    "BBS": "Bhubaneswar (BBS)",
    "SGUJ": "Siliguri (SGUJ)",
}

# 3. Railway Terminology Dictionary
RAILWAY_TERMS: Set[str] = {
    "train",
    "trains",
    "station",
    "stations",
    "platform",
    "platforms",
    "pnr",
    "coach",
    "coaches",
    "seat",
    "seats",
    "sleeper",
    "ac",
    "departure",
    "departures",
    "arrival",
    "arrivals",
    "boarding",
    "destination",
    "destinations",
    "origin",
    "origins",
    "today",
    "tomorrow",
    "morning",
    "afternoon",
    "evening",
    "night",
    "tatkal",
    "berth",
    "rajdhani",
    "shatabdi",
    "duronto",
    "vande bharat",
    "express",
}

# 4. Contextual Acoustic Corrections for Common STT Misrecognitions
# These patterns only activate when in a travel / railway contextual sentence
# or preceded/followed by prepositions like "from", "to", "at", "station", etc.
ACOUSTIC_PHONETIC_CORRECTIONS: List[Tuple[str, str, bool, str]] = [
    # (Regex pattern, replacement, requires_railway_context_flag, description)
    (r"\b(?:and|an|in|end)\s+jp\b", "NJP", True, "Phonetic correction 'and jp' -> 'NJP' in travel context"),
    (r"\bn\s+jp\b", "NJP", False, "Spelled out 'N JP' -> 'NJP'"),
    (r"\bn\.j\.p\.?\b", "NJP", False, "Abbreviation 'N.J.P.' -> 'NJP'"),
    (r"\bhow\s*rah\b", "Howrah", False, "Split name 'How rah' -> 'Howrah'"),
    (r"\bhaura\b", "Howrah", False, "Phonetic spelling 'Haura' -> 'Howrah'"),
    (r"\bhaora\b", "Howrah", False, "Bengali phonetic 'Haora' -> 'Howrah'"),
    (r"\bseal\s*dah\b", "Sealdah", False, "Split name 'Seal dah' -> 'Sealdah'"),
    (r"\bsealdaha\b", "Sealdah", False, "Phonetic 'Sealdaha' -> 'Sealdah'"),
    (r"\bsialdah\b", "Sealdah", False, "Phonetic 'Sialdah' -> 'Sealdah'"),
    (r"\bnew\s+jalpaiguri\b", "New Jalpaiguri", False, "Canonical 'New Jalpaiguri'"),
    (r"\bnew\s+jalpaigudi\b", "New Jalpaiguri", False, "Phonetic 'New Jalpaigudi' -> 'New Jalpaiguri'"),
    (r"\bnew\s+jolpaiguri\b", "New Jalpaiguri", False, "Phonetic 'New Jolpaiguri' -> 'New Jalpaiguri'"),
    (r"\bbardhaman\b", "Barddhaman", False, "Spelling 'Bardhaman' -> 'Barddhaman'"),
    (r"\bburdwan\b", "Barddhaman", False, "Alias 'Burdwan' -> 'Barddhaman'"),
    (r"\bbardwan\b", "Barddhaman", False, "Alias 'Bardwan' -> 'Barddhaman'"),
    (r"\bkharag\s*pur\b", "Kharagpur", False, "Split name 'Kharag pur' -> 'Kharagpur'"),
    (r"\bkaragpur\b", "Kharagpur", False, "Phonetic 'Karagpur' -> 'Kharagpur'"),
    (r"\bdurga\s*pur\b", "Durgapur", False, "Split name 'Durga pur' -> 'Durgapur'"),
    (r"\basan\s*sol\b", "Asansol", False, "Split name 'Asan sol' -> 'Asansol'"),
    (r"\bsili\s*guri\b", "Siliguri", False, "Split name 'Sili guri' -> 'Siliguri'"),
    (r"\bhowrah\s+junction\b", "Howrah Junction", False, "Canonical 'Howrah Junction'"),
    (r"\bnew\s+delhi\b", "New Delhi", False, "Canonical 'New Delhi'"),
    (r"\bcalcutta\b", "Kolkata", False, "Colloquial 'Calcutta' -> 'Kolkata'"),
]

# 5. Deepgram Keyterm Prompting List (for Deepgram Flux / Nova-3)
# Passed as repeated unweighted query parameters: keyterm=NJP&keyterm=New%20Jalpaiguri...
DEEPGRAM_KEYTERMS: List[str] = [
    # Station & location terms
    "NJP",
    "New Jalpaiguri",
    "Howrah",
    "Howrah Junction",
    "HWH",
    "Sealdah",
    "SDAH",
    "Kharagpur",
    "KGP",
    "Barddhaman",
    "Burdwan",
    "BWN",
    "Durgapur",
    "DGR",
    "Asansol",
    "ASN",
    "Malda",
    "Malda Town",
    "MLDT",
    "Siliguri",
    "SGUJ",
    "Kolkata",
    "KOAA",
    "New Delhi",
    "NDLS",
    "Delhi",
    "DLI",
    "Guwahati",
    "GHY",
    "Patna",
    "PNBE",
    "Ranchi",
    "RNC",
    "Bhubaneswar",
    "BBS",
    # Railway domain vocabulary
    "train",
    "station",
    "platform",
    "PNR",
    "coach",
    "seat",
    "sleeper",
    "AC",
    "departure",
    "arrival",
    "boarding",
    "destination",
    "origin",
    "tatkal",
    "berth",
    "Vande Bharat",
    "Rajdhani",
    "Duronto",
    "Shatabdi",
    "Express",
    # Temporal constraints
    "today",
    "tomorrow",
    "morning",
    "afternoon",
    "evening",
    "night",
]

# 6. Legacy Deepgram Nova-2 Boosted Keywords with Intensifiers (backward compatibility)
DEEPGRAM_KEYWORDS: List[str] = [
    "NJP:3",
    "New Jalpaiguri:2",
    "Howrah:2",
    "Howrah Junction:2",
    "Sealdah:2",
    "Kharagpur:2",
    "Barddhaman:2",
    "Burdwan:2",
    "Siliguri:2",
    "Durgapur:2",
    "Asansol:2",
    "Kolkata:2",
    "New Delhi:2",
    "Delhi:2",
    "Malda:2",
    "Patna:2",
    "Guwahati:2",
    "Ranchi:2",
    "Bhubaneswar:2",
    "HWH:2",
    "SDAH:2",
    "KOAA:2",
    "NDLS:2",
    "DLI:2",
    "KGP:2",
    "BWN:2",
    "PNR:2",
    "Vande Bharat:2",
    "Rajdhani:2",
    "Duronto:2",
    "Shatabdi:2",
    "tatkal:2",
    "sleeper:2",
]
